//
//  AppDelegate.m
//  InstagramX
//
//  Created by xcode on 6/18/18.
//  Copyright © 2018 MSCline. All rights reserved.
//

#import "AppDelegate.h"
#import "LoginViewController.h"
#import <Parse/Parse.h>  // directions are in swift (clean and rebuild)

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    [self setupParse];
    [self listenForLogoutNotification];
    [self skipLoginScreenIfLoggedIn];
    
    return YES;
}

- (void)applicationWillTerminate:(UIApplication *)application {
    [self logOutCurrentUser];
}

-(void)setupParse {

    // Initialize Parse
    // Set applicationId and server based on the values in the Heroku settings.
    // clientKey is not used on Parse open source unless explicitly configured

    [Parse initializeWithConfiguration: [ParseClientConfiguration configurationWithBlock: ^ (id < ParseMutableClientConfiguration > _Nonnull configuration) {

        // UPDATE APP ID, CLIENT ID, AND SERVER URL HERE
        configuration.applicationId = @"ancient-plateau-58463";
        configuration.clientKey = @"myMasterKey2sldkfjlskfjlskfjl";
        configuration.server = @"http://ancient-plateau-58463.herokuapp.com/parse";
        configuration.localDatastoreEnabled = NO;

        // If not correct, will get error message: "The data couldn’t be read because it isn’t in the correct format."  (Had trouble using a custom name, so use their autogenerated app name, not a url that you may have entered.  If you did enter something unique, then just change it back.
    }]];
}

-(void)skipLoginScreenIfLoggedIn {

    if ([PFUser currentUser] != nil) {

        [self setRootViewControllerHavingStoryBoardIdentifier:@"MainView"];  // Overriding Storyboard settings.
    }
}

-(void)listenForLogoutNotification {
    [[NSNotificationCenter defaultCenter] addObserverForName:@"didLogout" object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification * _Nonnull note) {

        [self logOutCurrentUser];
    }];
}

-(void)logOutCurrentUser {
    [PFUser logOutInBackgroundWithBlock:^(NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"%@", error.localizedDescription);
        } else {
            [self setRootViewControllerHavingStoryBoardIdentifier:@"LoginViewController"];
        }
    }];
}

-(void)setRootViewControllerHavingStoryBoardIdentifier: (NSString *)identifier {
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    LoginViewController *loginViewController = [storyboard instantiateViewControllerWithIdentifier:identifier];
    self.window.rootViewController = loginViewController;
}

@end
